# Generated by Django 2.1.5 on 2019-02-06 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190206_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padaria',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
